project:
  type: website
  output-dir: docs

website:
  title: Liam Connor
  favicon: images/favicon.png
  site-url: https://www.liamgconnor.com
  description: "Liam Connor's personal website."
  navbar:
    logo: images/logo.png
    logo-alt: "LC"
    # pinned: True
    search: true
    background: primary
    title: False
    left:
      - href: index.qmd
        text: About Me
      - href: projects/index.qmd
        text: Projects
    right:
      - icon: envelope
        target: _blank
        aria-label: email
        href: "mailto:my_email_is:firstname.lastname@duke.edu"
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/liam-g-connor/
        target: _blank
      - icon: github
        menu:
          - text: Website Code
            url:  https://github.com/slc99/personal_site
            target: _blank
          - text: Report a Bug
            url:  https://github.com/slc99/personal_site/issues
            target: _blank
  page-footer:
    border: true
    left: |
      Powered by [{{< iconify simple-icons quarto size=small >}}](https://quarto.org/) | Hosted with [{{< iconify simple-icons github >}}](https://pages.github.com/)
    right: |
      Â© 2025 [Liam Connor](/index.qmd) | [MIT License](/license.qmd)

format:
  html:
    theme:
      light: [flatly, scss/light.scss]
    css: scss/styles.css
    code-link: true
    link-external-newwindow: true
    smooth-scroll: true
    highlight-style: gruvbox


# resources:
#   - CNAME

