project:
  type: website
  output-dir: docs

website:
  title: "Liam Connor's Personal Website"
  favicon: images/apple-touch-icon.png
  site-url: https://www.liamgconnor.com
  description: "Liam Connor's personal website. Projects, musing, resume, and more"
  navbar:
    search: true
    background: primary
    title: "Liam Connor"
    left:
      - href: index.qmd
        text: About me
      - href: projects.qmd
        text: Projects
    right:
      - icon: github
        aria-label: github
        target: _blank
        href: https://github.com/slc99
      - icon: envelope
        target: _blank
        aria-label: email
        href: "mailto:fake@outlook.com"
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/liam-g-connor/
        target: _blank
  
body-header: | 
  This page brought to you by <https://example.com>

format:
  html:
    theme:
      light: [flatly, scss/light.scss]
    css: scss/styles.css
    code-link: true
    # link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    highlight-style: gruvbox


# resources:
#   - CNAME

