project:
  type: website
  output-dir: docs

website:
  title: "Liam Connor's Personal Website"
  favicon: images/apple-touch-icon.png
  site-url: https://www.liamgconnor.com
  description: "Liam Connor's personal website. Projects, musing, resume, and more"
  navbar:
    logo: images/logo.png
    logo-alt: "LC"
    search: true
    background: primary
    title: False
    left:
      - href: index.qmd
        text: About me
      - href: projects.qmd
        text: Projects
    right:
      - icon: envelope
        target: _blank
        aria-label: email
        href: "mailto:fake@outlook.com"
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/liam-g-connor/
        target: _blank
      - icon: github
        target: _blank
        menu:
          - text: Website Code
            url:  https://github.com/slc99/personal_site
          - text: Report a Bug
            url:  https://github.com/slc/personal_site/issues
  page-footer:
    border: true
    left: |
      Published with [{{< iconify simple-icons quarto size=small >}}](https://quarto.org/) | Hosted by [{{< iconify simple-icons github >}}](https://pages.github.com/)
    right: |
      Â© 2025 [Liam Connor](/index.qmd) | [MIT License](license.qmd)

format:
  html:
    theme:
      light: [flatly, scss/light.scss]
    css: scss/styles.css
    code-link: true
    link-external-newwindow: true
    smooth-scroll: true
    highlight-style: gruvbox


# resources:
#   - CNAME

